# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 319)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(310, 220, 75, 23))
        self.submit_button.setObjectName("submit_button")
        self.grade_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.grade_label.setGeometry(QtCore.QRect(50, 70, 121, 81))
        self.grade_label.setObjectName("grade_label")
        self.student_number_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.student_number_label.setGeometry(QtCore.QRect(30, 20, 191, 41))
        self.student_number_label.setObjectName("student_number_label")
        self.student_name_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.student_name_text.setGeometry(QtCore.QRect(280, 30, 121, 31))
        self.student_name_text.setObjectName("student_name_text")
        self.student_score_text = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.student_score_text.setGeometry(QtCore.QRect(280, 100, 121, 31))
        self.student_score_text.setObjectName("student_score_text")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(110, 220, 75, 23))
        self.add_button.setObjectName("add_button")
        self.description_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.description_label.setGeometry(QtCore.QRect(80, 160, 331, 41))
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Final Project"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.grade_label.setText(_translate("MainWindow", "Student (name)\'s Score"))
        self.student_number_label.setText(_translate("MainWindow", "Please enter the name of the student"))
        self.add_button.setText(_translate("MainWindow", "Add"))
        self.description_label.setText(_translate("MainWindow", "When finished with all students, please press submit for results."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
